#
# Copyright (C) 37 Audits - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Written by Thiago Moreira <thiago.moreira@37audits.com>
#

defaultLogLevel=INFO
showLogName=true